### ISSUE TITLE
Handle messenger.com too

### ISSUE THREAD

**Issue by johan** [Morhaus/facebook-sixth-sense#3]
Way cool – [your blog post](http://kirszenberg.com/facebook-sixth-sense) was a fun read!

May I ask for manifest coverage of the stand-alone [Facebook Messenger](https://www.messenger.com/) site, too?

If you ever want to work at the internal codebases at Facebook (or on Messenger, for that matter) directly, you would probably not find it hard to get your foot in. :-)

**Comment by alexkirsz** [comment]
[Well, that was easy!](https://github.com/Morhaus/facebook-sixth-sense/commit/c24944da8cc2a5f111c63d2373450805dc484692)

I've updated the app to 1.2. Since the app requires new permissions (_://messenger.com/_), the extension will be disabled until the user manually re-enable it. See [Examples of permission warnings](https://developer.chrome.com/extensions/permission_warnings#examples).

I hope that won't cause too much confusion!

**Comment by alexkirsz** [comment]
Oh, and thanks for the kind words and the suggestion! :)
